### ISSUE TITLE
Slack mentions enricher

### ISSUE THREAD

**Issue by otherguy** [robusta-dev/robusta#1174]
All our workloads, pods, deployments, HPAs, etc. are tagged with labels for a) which team owns them and b) with who to notify when something is wrong with them. The details of the latter are not important since we control the label. It can be whatever works best, for example a comma separated string of Slack IDs.

For our Slack sink, I would love it if Robusta could @-mention the people that should be notified about issues with the deployment or pod. 

For example if there is an `on_pod_oom_killed` event, Robusta could enrich the slack message with a `@username` in Slack.

**Comment by arikalon1** [comment]
Hi @jmalloc , @otherguy 

We're considering implementing it using slack user/groups instead of names.
So, in order to mention a slack user or group, you'll need to provide their ids (you can get it from your Slack workspace)
Mentions works with ids, and to get id by name, our Slack api key need additional permissions, and we're trying to avoid that.

Will that be an acceptable solution?

**Comment by otherguy** [comment]
@arikalon1 sounds good to me :) I mentioned IDs in the original request because I figured you would want to avoid adding additional permissions!

**Comment by pavangudiwada** [comment]
Closing as the feature is released!

**Comment by otherguy** [comment]
@pavangudiwada awesome, thanks! Is there documentation for it?

**Comment by pavangudiwada** [comment]
@otherguy Yes, here you go: https://docs.robusta.dev/master/configuration/sinks/slack.html#automatically-mentioning-users

**Comment by otherguy** [comment]
Super cool, thank you so much @pavangudiwada and @arikalon1!
