### ISSUE TITLE
Helm chart defaults to runner image version 0.0.0, which doesn't exist.

### ISSUE THREAD

**Issue by tim-sendible** [robusta-dev/robusta#146]
**Describe the bug**
Helm values file is defaulted to runner version 0.0.0, which causes the installation documented on the website to fail.

**To Reproduce**
1. Go to https://docs.robusta.dev/master/getting-started/installation.html and follow the instructions.

The runner never deploys because the image tag is defaulted to 0.0.0

**Expected behavior**
I should be able to install this like a normal Helm chart, with sensible defaults.

**Comment by aantn** [comment]
Thank you for reporting this. I'm looking into it and have a few questions.

1. Are you installing Robusta via the chart at `https://robusta-charts.storage.googleapis.com` or using the chart contained in the GitHub repository? (I just ran the exact instructions you linked and for me it succeeds.)

2. What is the output of `helm version`?

## Additional context
I'll try to explain here the motivation of using a placeholder 0.0.0 in chart as stored in GitHub. I'm sharing it in case you have a better recommendation for how we can work.

We're trying to support two workflows:

1. We want to do releases of Robusta via GitHub actions and automatically upload a Helm chart to our GCP bucket (https://robusta-charts.storage.googleapis.com) with the correct version so there is no room for error.

2. You are developer or want to install the runner directly from source. You build using skaffold and skaffold automatically patches the Helm chart to use the Docker images that you just built. In this case we don't want to hardcode a version in the git version of the chart, because you want to use the version you just built and not a prebuilt version.

If you're interested in the second case, let me know. We haven't yet tested it outside our organization and we might need to modify it to support users without access to our GCR image registry.

**Comment by tim-sendible** [comment]
I'm installing via the repo, but using the values.yaml housed in the corresponding github release so that I can install this using gitops (argocd) and so that I can avoid using the bonkers python script that generates the values file for me.

I'm sure you are aware, you can pin a default image tag to a helm chart version, so I find it odd to reinvent the wheel using a placeholder like this.

Chart version is 0.8.11, but I suspect this isn't relevant.

**Comment by aantn** [comment]
@tim-sendible does running `helm show values robusta/robusta` help?

We are indeed trying to pin a default image tag, but it only gets pinned in the released chart (https://robusta-charts.storage.googleapis.com) and not in the GithHub repository itself.

**Comment by aantn** [comment]
@tim-sendible I've updated the docs to explain how you can install without the CLI and where to take the `values.yaml` from.

https://docs.robusta.dev/master/getting-started/installation.html#alternative-installation-methods

Does this help fix the confusion? Is there anything else you recommend we change here? (Feel free to provide a link to another project with a more intuitive installation as reference.)

**Comment by aantn** [comment]
I'm closing this for now. If you have more suggestions for improving this, feel free to reopen.
