### ISSUE TITLE
Hierarchy for robusta playbooks

### ISSUE THREAD

**Issue by kranurag7** [robusta-dev/robusta#248]
- As of now all the robusta playbooks are within one single [folder](https://github.com/robusta-dev/robusta/tree/master/playbooks/robusta_playbooks)
- We are intending to add many more playbooks in the future [Reference](https://youtu.be/oavP7M5P8xY).
- We need to set up the hierarchy either based on k8s resources or based on different categories.

**Comment by aantn** [comment]
+1

@arikalon1 any thoughts on how we should organize them?

**Comment by arikalon1** [comment]
Can we organize playbooks in separated playbook repos?
Will that be good enough?

**Comment by aantn** [comment]
I'm not sure. I'm in favor of keeping most of the playbooks in the current repo so using them is smoother and we can release them alongside Robusta versions.

However, we already have 30 or so files in the robusta_playbooks directory. In the docs we're organizing them by category, but in the source code we're not. 

For me it's easy to find what I'm looking for because I wrote it and know where to look. For new contributors I think it's probably much harder.

**Comment by kranurag7** [comment]
I agree with @aantn in this case. For new contributors it's tough to find. Also in future if we will get more actions live then it will be easy to document and if we maintain a hierarchy then filtering out will be smooth as well.

**Comment by arikalon1** [comment]
ok. So splitting the playbooks into logical categories, where each category is a folder?
What categories would you choose?

**Comment by aantn** [comment]
It's been two years, so closing this. We're OK keeping the current organization for now.
