### ISSUE TITLE
Authentication via Keycloak

### ISSUE THREAD

**Issue by ath88** [robusta-dev/robusta#430]
Please make it possible for us to authenticate via our self hosted Keycloak. :)

**Comment by Sheeproid** [comment]
Hey @ath88 . Since Keycloak is a self hosted solution, it can only be used in self hosted environment hence cannot be connected to the Robusta SaaS.

**Comment by ath88** [comment]
I believe your conclusion is wrong. Sure it's not an easy fix, but allowing organizations to specify their own OpenID Connect Identity Provider should indeed be possible.

How did you get to your conclusion that it cannot be done? :)

**Comment by Sheeproid** [comment]
Hey @ath88 , sure, I'll explain.

Robusta UI authentication is based on Supabase.

After reading the instructions here:
https://supabase.com/docs/guides/auth/auth-keycloak#add-login-code-to-your-client-app

And checking out the Authentication providers page, and opening Keycloak:
![Screen Shot 2022-07-19 at 8 27 58](https://user-images.githubusercontent.com/679727/179672125-0e501f29-6099-4175-82d3-3535b0e7ae4e.png)

My conclusion is that Keycloak can only be used once, and not for each organization.

However, in the self hosted version of Robusta, it is probably possible because the self-hosted Robusta has a copy of Supabase built-in:  https://docs.robusta.dev/master/user-guide/self-hosting.html

**Comment by ath88** [comment]
I understand the issue, but I still insist that it has nothing to do with Keycloak being self hosted, but rather a technical limitation of Supabase. :)

I'll be opening an issue with gotrue to try and make it possible to configure multiple Identity Providers of the same type. Once that is possible, it'll be possible to allow to authenticate against your clients identity providers.
