### ISSUE TITLE
Error Image Pull

### ISSUE THREAD

**Issue by aashish-fiftyfive** [robusta-dev/robusta#823]
Hi there,

I am facing issues with the docker image pull for runner deployment, here is the following error -

```Failed to pull image "us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-runner:0.0.0": rpc error: code = NotFound desc = failed to pull and unpack image "us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-runner:0.0.0": failed to resolve reference "us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-runner:0.0.0": us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-runner:0.0.0: not found```

Is anyone else is facing same error?

**Comment by aashish-fiftyfive** [comment]
Yes it helps but now facing another error -

```Message: "Error configuring sink dev_sink of type <class 'robusta.core.sinks.slack.slack_sink_params.SlackSinkConfigWrapper'>: The request to the Slack API failed. (url: https://www.slack.com/api/auth.test)\nThe server responded with: {'ok': False, 'error': 'invalid_auth'}"```

In api_url I am passing the webhook URL of Slack, do I need to pass any other thing in that?

**Comment by arikalon1** [comment]
Robusta sends notification to `sinks`
Slack is one type of `sink`

In order to use Slack `sink` your `generated_values.yaml` should contain something like:
```
sinksConfig:
- slack_sink:
    api_key: xoxb-...
    name: main_slack_sink
    slack_channel: my-slack-channel

```

The `api_key` is a key you receive when you connect the Robusta Slack app to you Slack workspace.
You can do it by running `robusta gen-config` which generates a full `generated_values.yaml` file, or by running `robusta integrations slack` that generates only the `sink` configuration part.

Does that help?

**Comment by arikalon1** [comment]
hi @maha885 
I'm not sure is this issue requires fixing something, or it's a misconfiguration 

Lets wait to @aashish-fiftyfive 's response

**Comment by aashish-fiftyfive** [comment]
I have solved the issue, you can close this Issue @arikalon1

**Comment by arikalon1** [comment]
closing. Thanks for the update @aashish-fiftyfive
